# Generated by Django 3.0.8 on 2020-07-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='image',
            field=models.ImageField(blank=True, upload_to='photo/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='place',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
