# Generated by Django 3.0.8 on 2020-07-22 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20200722_2207'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name_plural': 'Места'},
        ),
    ]
